### ISSUE TITLE
Bézier envelope extension cannot deal with Circle objects that have been converted to path

### ISSUE THREAD

**Issue by Moini** [shlomif/Bezier-Envelope-for-Inkscape#2]
If one tries to use a circle that has been converted to path as envelope (four nodes, see discussion thread here: http://www.inkscapeforum.com/viewtopic.php?f=5&t=32223), then the extension doesn't work, because it doesn't support the segment type.

Would there be a chance that support for segment type 'A' (and maybe more) could be added? I don't know enough about SVG paths to be able to do it myself.

Workaround: 
- switch to node tool and trigger a path rewrite. This can be done by moving a node, or by changing the node type of all nodes to cusp.

**Comment by shlomif** [comment]
HI @Moini ! Unfortunately, I did not originate this ext - just received it and distributed it. Fixing this problem will require some time and research, and I personally lack the need. PRs / patches are welcome, though.

**Comment by Moini** [comment]
Oh, hi, Shlomi :) Thanks for the reply! I don't know if it helps, but some repos here use a 'help wanted' tag for issues such as these.

**Comment by superchap** [comment]
Help?
[Screen captures attached]
I'm using Inkscape 0.91 r13725 on Linux Mint
This ...
            GNU GENERAL PUBLIC LICENSE
               Version 2, June 1991
 Copyright (C) 1989, 1991 Free Software Foundation, Inc.
 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

While following these instructions --> https://youtu.be/ldbdhVWaT20, I get this Inkscape error message: 

"Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected."

Traceback (most recent call last):
  File "bezierenvelope.py", line 381, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "bezierenvelope.py", line 90, in effect
    raise Exception, "Both letter and envelope must be SVG paths."
Exception: Both letter and envelope must be SVG paths.

Can you help? I would REALLY like to be able to take advantage of this extension. VERY COOL! Thanks in advance.

{again, see screen shots}
![BezierEnvelope issue capture 1](https://user-images.githubusercontent.com/6477792/57198067-3504cb80-6f34-11e9-9171-82b206835a35.png)
![BezierEnvelope issue capture 2](https://user-images.githubusercontent.com/6477792/57198068-359d6200-6f34-11e9-86c9-a2d903b6f155.png)
![BezierEnvelope issue capture 3](https://user-images.githubusercontent.com/6477792/57198069-359d6200-6f34-11e9-9b4e-845d069201c6.png)
![BezierEnvelope issue capture 4](https://user-images.githubusercontent.com/6477792/57198070-359d6200-6f34-11e9-8c76-6ebac427c0a9.png)
